package goncordia

import (
	"context"
	"fmt"
	"log/slog"
	"sync/atomic"
	"time"

	"github.com/kirimatt/goncordia/clock"
	"github.com/kirimatt/goncordia/core"
	"github.com/kirimatt/goncordia/driver"
)

// PeriodicJob pairs a Schedule with the job args to enqueue on each tick.
type PeriodicJob struct {
	// Schedule determines when the job runs.
	Schedule core.Schedule
	// Args is the job to enqueue.
	Args core.JobArgs
	// Opts are passed through to Enqueue on each tick (optional).
	Opts *core.InsertOpts
}

// CronConfig configures a CronScheduler.
type CronConfig struct {
	// TickInterval controls how often the scheduler checks for due jobs.
	// Default: 1 second.
	TickInterval time.Duration
	// Clock overrides the time source. Defaults to clock.Real{}.
	Clock clock.Clock
	// LeaderName identifies this scheduler group. Only one live instance in the
	// group enqueues periodic jobs. Default: "goncordia-cron".
	LeaderName string
	// WorkerID identifies this scheduler instance. A random ID is generated by default.
	WorkerID string
	// LeaderTTL is the lease duration on non-advisory-lock backends. Default: 30 seconds.
	LeaderTTL time.Duration
	// ErrorHandler receives leader-election and enqueue errors. Default: slog.Error.
	ErrorHandler func(error)
}

// CronScheduler enqueues periodic jobs on a configurable tick.
// It does not process jobs — pair it with a WorkerPool.
//
// Usage:
//
//	cs := goncordia.NewCronScheduler(d, []goncordia.PeriodicJob{
//	    {Schedule: core.Every(time.Hour), Args: CleanupArgs{}},
//	}, goncordia.CronConfig{})
//	go cs.Start(ctx)
type CronScheduler[TTx any] struct {
	client  *Client[TTx]
	entries []cronEntry
	config  CronConfig
	started atomic.Bool
}

type cronEntry struct {
	job     PeriodicJob
	lastRun time.Time
}

// NewCronScheduler creates a CronScheduler backed by d.
// jobs is the list of periodic jobs to manage.
func NewCronScheduler[TTx any](d driver.Driver[TTx], jobs []PeriodicJob, cfg CronConfig) *CronScheduler[TTx] {
	if cfg.TickInterval <= 0 {
		cfg.TickInterval = time.Second
	}
	if cfg.Clock == nil {
		cfg.Clock = clock.Real{}
	}
	if cfg.LeaderName == "" {
		cfg.LeaderName = "goncordia-cron"
	}
	if cfg.WorkerID == "" {
		cfg.WorkerID = newWorkerID()
	}
	if cfg.LeaderTTL <= 0 {
		cfg.LeaderTTL = 30 * time.Second
	}
	if cfg.ErrorHandler == nil {
		cfg.ErrorHandler = func(err error) { slog.Error("goncordia cron error", "error", err) }
	}

	entries := make([]cronEntry, len(jobs))
	for i, j := range jobs {
		entries[i] = cronEntry{job: j}
	}

	return &CronScheduler[TTx]{
		client:  NewClient[TTx](d, ClientConfig{Clock: cfg.Clock}),
		entries: entries,
		config:  cfg,
	}
}

// Start begins the scheduling loop. It blocks until ctx is cancelled.
func (s *CronScheduler[TTx]) Start(ctx context.Context) error {
	if !s.started.CompareAndSwap(false, true) {
		return fmt.Errorf("cron scheduler already started")
	}
	ticker := s.config.Clock.NewTicker(s.config.TickInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-ticker.C():
			s.tick(ctx)
		}
	}
}

func (s *CronScheduler[TTx]) tick(ctx context.Context) {
	elected, err := s.client.driver.Executor().LeaderAttemptElect(ctx, driver.LeaderElectParams{
		Name:     s.config.LeaderName,
		WorkerID: s.config.WorkerID,
		TTL:      s.config.LeaderTTL,
	})
	if err != nil {
		s.config.ErrorHandler(fmt.Errorf("cron leader election: %w", err))
		return
	}
	if !elected {
		return
	}
	now := s.config.Clock.Now()
	for i := range s.entries {
		e := &s.entries[i]
		next := e.job.Schedule.Next(e.lastRun)
		if next.IsZero() || !now.Before(next) {
			if _, err := s.client.Enqueue(ctx, e.job.Args, e.job.Opts); err != nil {
				s.config.ErrorHandler(fmt.Errorf("enqueue periodic job %q: %w", e.job.Args.Kind(), err))
				continue
			}
			e.lastRun = now
		}
	}
}
